# Experimental artifact only. Invoke with -C pointing at an isolated build dir.
srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
include ${srcdir}/../../../makefile-common

.PHONY: all
all: whole_gemm.xclbin

rep_elan_bf16.o: ${srcdir}/../kernels/rep_elan_bf16.cc
	${PEANO_INSTALL_DIR}/bin/clang ${PEANOWRAP2P_FLAGS} -c $< -o $@

whole_gemm.mlir: ${srcdir}/aie2_whole_gemm.py ${srcdir}/aie2_gemm_conv1x1.py
	python3 $< > $@

whole_gemm.xclbin: whole_gemm.mlir rep_elan_bf16.o
	aiecc.py --aie-generate-xclbin --aie-generate-npu-insts --no-compile-host --no-xchesscc --no-xbridge --xclbin-name=$@ --npu-insts-name=whole_gemm.bin $<
