# Experimental arithmetic proof only; use an isolated build directory.
srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
include ${srcdir}/../../../makefile-common

.PHONY: all
all: phase_a_shard.xclbin phase_a_shard.bin phase_a_pool.xclbin phase_a_pool.bin

phase_a_shard.o: ${srcdir}/phase_a_shard.cc ${srcdir}/../kernels/rep_elan_bf16.cc ${srcdir}/../kernels/mmul_bf16_rows.h
	${PEANO_INSTALL_DIR}/bin/clang ${PEANOWRAP2P_FLAGS} -c $< -o $@

phase_a_shard.mlir: ${srcdir}/aie2_phase_a_shard.py
	python3 $< > $@

phase_a_pool.mlir: ${srcdir}/aie2_phase_a_shard.py
	python3 $< --pool-only > $@

phase_a_shard.xclbin phase_a_shard.bin &: phase_a_shard.mlir phase_a_shard.o
	aiecc.py --aie-generate-xclbin --aie-generate-npu-insts --no-compile-host --no-xchesscc --no-xbridge --xclbin-name=phase_a_shard.xclbin --npu-insts-name=phase_a_shard.bin $<

phase_a_pool.xclbin phase_a_pool.bin &: phase_a_pool.mlir phase_a_shard.o
	aiecc.py --aie-generate-xclbin --aie-generate-npu-insts --no-compile-host --no-xchesscc --no-xbridge --xclbin-name=phase_a_pool.xclbin --npu-insts-name=phase_a_pool.bin $<
