# Build only experimental artifacts in the caller's chosen working directory.
srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
include ${srcdir}/../../../makefile-common

.PHONY: all
all: single.xclbin chain.xclbin

rep_elan_bf16.o: ${srcdir}/../kernels/rep_elan_bf16.cc ${srcdir}/../kernels/mmul_bf16_rows.h
	${PEANO_INSTALL_DIR}/bin/clang ${PEANOWRAP2P_FLAGS} -c $< -o $@

single.mlir: ${srcdir}/aie2_bo_reuse.py
	python3 $< 1 > $@

chain.mlir: ${srcdir}/aie2_bo_reuse.py
	python3 $< 2 > $@

%.xclbin: %.mlir rep_elan_bf16.o
	aiecc.py --aie-generate-xclbin --aie-generate-npu-insts --no-compile-host --no-xchesscc --no-xbridge --xclbin-name=$@ --npu-insts-name=$*.bin $<
