# Experimental artifact only. Invoke with -C pointing at an isolated build dir.
srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
include ${srcdir}/../../../makefile-common

.PHONY: all
all: whole_conv.xclbin

rep_elan_bf16.o: ${srcdir}/../kernels/rep_elan_bf16.cc ${srcdir}/../kernels/mmul_bf16_rows.h
	${PEANO_INSTALL_DIR}/bin/clang ${PEANOWRAP2P_FLAGS} -c $< -o $@

whole_conv.mlir: ${srcdir}/aie2_whole_conv.py ${srcdir}/aie2_multicore.py
	python3 $< > $@

whole_conv.xclbin: whole_conv.mlir rep_elan_bf16.o
	aiecc.py --aie-generate-xclbin --aie-generate-npu-insts --no-compile-host --no-xchesscc --no-xbridge --xclbin-name=$@ --npu-insts-name=whole_conv.bin $<
