# kernel.py -*- Python -*-
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc.

"""PythoC kernel wrapper for IRON.

Provides PythocKernel class that integrates PythoC-compiled kernels
into IRON programs.
"""

from pathlib import Path
from typing import Optional
import numpy as np

from ..kernel import Kernel


class PythocKernel(Kernel):
    """IRON Kernel wrapper for PythoC-compiled functions.

    This class extends IRON's Kernel to support PythoC-compiled kernels.
    It accepts AIE object files (.o) generated by the PythoC compiler.
    Inline kernels are compiled on construction and also yield .o files.

    Example (External):
        from aie.iron.pythoc import compile_pythoc_kernel, PythocKernel

        obj_file = compile_pythoc_kernel(
            "pythoc_kernels/mul.py",
            "eltwise_mul_vectorized_i32"
        )

        kernel = PythocKernel(
            "eltwise_mul_vectorized_i32",
            str(obj_file),
            [tile_ty, tile_ty, tile_ty]
        )
    """

    def __init__(
        self,
        kernel_fn_or_name: str,
        llvm_ir_path_or_types: str | list,
        types: Optional[list[type[np.ndarray] | np.dtype]] = None,
        target_arch: str = "aie2p",
        extra_globals: Optional[dict] = None,
        helpers: Optional[list] = None,
    ):
        """Initialize PythocKernel.

        Args:
            kernel_fn_or_name: Function name (Phase 1) or decorated function (Phase 2)
            llvm_ir_path_or_types: Path to object file (.o) (Phase 1) or type list (Phase 2)
            types: Type signature (Phase 1 only, when llvm_ir_path is string)
            target_arch: Target architecture (aie2, aie2p)
            extra_globals: Additional symbols (e.g. register constants) for compilation
            helpers: List of @aie_kernel helper functions to compile alongside
                     the main kernel.  Their source is prepended so the main
                     kernel can call them.

        Raises:
            NotImplementedError: If trying to use Phase 2 features
            TypeError: If arguments are invalid
        """
        # External object file
        if isinstance(kernel_fn_or_name, str):
            if not isinstance(llvm_ir_path_or_types, str):
                raise TypeError(
                    "For external kernels, llvm_ir_path_or_types must be a string path"
                )
            if types is None:
                raise TypeError("For external kernels, types parameter is required")

            # Validate object file exists
            obj_path = Path(llvm_ir_path_or_types)
            if not obj_path.exists():
                raise FileNotFoundError(f"Object file not found: {obj_path}")

            # Call parent Kernel constructor with object file
            super().__init__(
                name=kernel_fn_or_name, object_file_name=str(obj_path), arg_types=types
            )

            self._target_arch = target_arch

        elif hasattr(kernel_fn_or_name, "__aie_kernel__"):
            # Inline decorated function
            # Import compile_pythoc_source here to avoid circular imports
            from .compiler import compile_pythoc_source
            import textwrap

            # Build combined source: helpers first, then main kernel.
            # compile_pythoc_source compiles all helper FunctionDefs
            # before the target, so calls from main→helper resolve.
            source_parts = []
            for h in helpers or []:
                if not hasattr(h, "__aie_source__"):
                    raise TypeError(
                        f"Helper {h!r} must be decorated with @aie_kernel"
                    )
                source_parts.append(textwrap.dedent(h.__aie_source__))
            source_parts.append(textwrap.dedent(kernel_fn_or_name.__aie_source__))
            combined_source = "\n".join(source_parts)

            # Compile the inline function to LLVM IR
            obj_file = compile_pythoc_source(
                source_code=combined_source,
                function_name=kernel_fn_or_name.__aie_name__,
                target_arch=target_arch,
                output_dir=None,
                optimization_level=2,
                verbose=False,
                extra_globals=extra_globals,
            )

            # Validate types parameter
            if not isinstance(llvm_ir_path_or_types, list):
                raise TypeError(
                    "For inline kernels, llvm_ir_path_or_types must be a list of types"
                )

            # Call parent Kernel constructor with compiled object file
            super().__init__(
                name=kernel_fn_or_name.__aie_name__,
                object_file_name=str(obj_file),
                arg_types=llvm_ir_path_or_types,
            )

            self._target_arch = target_arch
            self._is_inline = True

        else:
            raise TypeError(
                "kernel_fn_or_name must be either a string (function name) "
                "or a function decorated with @aie_kernel"
            )
